### ISSUE TITLE
Clean up example

### ISSUE THREAD

**Issue by ai** [TCotton/postcss-mq-keyframes#1]
Your input/output example contains too many irrelevant code, it is difficult to find diff.

I think your example can be with 4-5 lines of code.

**Comment by TCotton** [comment]
done

**Comment by ai** [comment]
It is still too long. Why not:

``` css
@media only screen and (min-width: 415px) {

    .pace {
        animation: pace-anim 5s;
    }

    @keyframes pace-anim {
        100% {
            opacity: 0;
        }
    }

}
```
